In [ ]:
#!/usr/bin/env python
# coding: utf-8

# In[16]:


#설정변경코드
#변수 명이 두번 이상 출력되어도 모두 콘솔에서 보여줄 것
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

# InteractiveShell.ast_node_interactivity : 'all' | 'last' | 'last_expr' | 'none' (기본값은 'last_expr')


# In[2]:


# 모듈 import 
import numpy as np
import pandas as pd


# ### pandas 데이터처리 및 변환 관련 함수

# ### 데이터 개수 세기
# - 가장 간단한 분석은 개수를 세는 것임
# - count() 함수 이용
#     - NaN 값은 세지 않는다

# In[3]:


#  시리즈에서 개수 세기
s = pd.Series(range(10))
s[3] =np.nan
s


# In[4]:


s.count()


# ### 난수
# 
# - 난수 : seed(값) 라는 함수를 사용할 수 있음
# - seed의 의미 : 난수 알고리즘에서 사용하는 기본 값으로
#     - 시드값이 같으면 동일한 난수가 발생함
#     

# In[10]:


np.random.seed(3) # 난수값을 고정하기위해 난수발생함수와 반드시 같이 사용
np.random.randint(5, size=4)


# In[15]:


np.random.randint(5, size=4) # seed() 함수가 같이 실행되지 않기때문에 실행시마다 다른 결과 반환


# In[18]:


# 예제 데이터 프레임 생성
# 데이터 0-4범위의 난수 발생, 4행4열, 실수형데이터로 생성
# np.random.seed(3)
# df=pd.DataFrame(np.random.randint(5,size=(4,4)),dtype=float)
# df
np.random.seed(3)
df1=pd.DataFrame(np.random.randint(5,size=(4,4))) #기본 정수

df1.iloc[2,3] =np.nan
df1


# In[19]:


# df의 count()는 각 열에 대한 연산을 진행 - 각열의 유효한 원소의 개수를 반환
df1.count()


# ##### count  함수 사용 예제 (titanic 데이터 활용)

# - 타이타닉 승객 데이터 사용
#     - seaborn 패키지 내에 data로 존재
#     - 데이터셋 읽어오기 : 패키지명.load_dataset("data명")

# In[20]:


import seaborn as sns  # 그래프 패키지

titanic = sns.load_dataset('titanic')
titanic.head(10)


# In[22]:


# titanic df 의 각 열의 원소 개수를 산출 - count() 함수
titanic.shape
titanic.count() # 시리즈 반환 - 전체 행에 대해 값 차이가 나는 열은 결측치가 있다는 의미


# ###  카테고리 값 세기
# - 시리즈의 값이 정수,문자열 등 카테고리 값인 경우에
# - 시리즈.value_counts()메서드를 사용해 각각의 값이 나온 횟수를 셀 수 있음
# - 파라미터 normalize=True 를 사용하면 각 값 및 범주형 데이터의 비율을 계산
#     - 시리즈.value_counts(normalize=True)

# In[25]:


np.random.seed(1)
s2 = pd.Series(np.random.randint(6,size=100))
s2.head(10)
s2.tail()
len(s2)


# In[26]:


s2.value_counts() # 0,1,2,3,4,5 각 값이 몇번 나왔는지 결과 반환


# ##### 범주형 데이터에 value_counts() 함수 적용
# - 범주형 데이터 : 관측 결과가 몇개의 범주 또는 항목의 형태로 나타나는 자료
#     - ex. 성별(남,여), 선호도(좋다, 보통, 싫다), 혈액형(A,B,O,AB) 등

# In[29]:


titanic.head(2)


# In[31]:


# alive 열 : 생존여부  yes/no 로 표시되어 있음
titanic['alive'].dtype #dtype('O') Object type
titanic['alive'].value_counts()


# In[33]:


# 생존자/ 사망자 비율 계산
titanic['alive'].value_counts(normalize=True)
titanic['alive'].value_counts(normalize=True)*100


# ##### 데이터프레임에 value_counts() 함수 사용
# - 행을 하나의 value로 정의 동일한 행이 몇번 나타났는지를 반환
# - 행 데이터의 경우가 인덱스 설정  개수된 값이 value로 표시되는 Series 반환

# In[34]:


# 예제 df
df = pd.DataFrame({'num_legs': [2, 4, 4, 6],
                   'num_wings': [2, 0, 0, 0]},
                  index=['falcon', 'dog', 'cat', 'ant'])
df


# In[37]:


df.value_counts().index
df.value_counts()


# In[38]:


# 예제 df
df1


# In[39]:


df1.value_counts() # 행 원소로  NaN값이 있는 필드는 개수하지 않는다


# In[40]:


df1.value_counts().shape
df1.value_counts().sort_index().index


# ### 데이터 정렬 - 정렬 함수 사용
# - sort_index() : 인덱스를 기준으로 정렬
# - sort_value() : 데이터 값을 기준으로 정렬

# #### 시리즈 정렬
#     - ascending=True/False : 오름차순/내림차순
#     - 생략하면 오름차순

# In[41]:


# 예제 시리즈
s2


# In[45]:


s2.value_counts() # 반환 값을 기준으로 정렬된 시리즈
s2.value_counts().sort_index() # 인덱스 기준 정렬 : 오름차순
s2.value_counts().sort_index(ascending=False) #  인덱스 기준 정렬 : 내림차순


# In[47]:


s2.value_counts().sort_values(ascending=True) # 원소값 기준 오름차순 정렬
s2.value_counts().sort_values(ascending=False) # 원소값 기준 내림차순 정렬


# In[48]:


s2.sort_values()


# ### 데이터 프레임 정렬
# 
# - df.sort_values() : 특정열 값 기준 정렬
#     - 데이터프레임은 2차원 배열과 동일하기 때문에
#         - 정렬시 기준열을 줘야 한다. by 인수 사용 : 생략 불가
#         - by = 기준열, by=[기준열1,기준열2]
#     - 오름차순/내림차순 : ascending = True/False (생략하면 오름차순)
# - df.sort_index() : DF의 INDEX 기준 정렬
#     - 오름차순/내림차순 : ascending = True/False (생략하면 오름차순)

# In[49]:


# 예제 df1
df1


# In[51]:


# df1.sort_values() #sort_values() missing 1 required positional argument: 'by'


# In[52]:


df1.sort_values(by=0,ascending=True) #0번열 기준 오름차순 정렬


# In[53]:


df1.sort_values(by=0,ascending=False) #0 번열 기준 내림차순 정렬


# In[54]:


df1.sort_values(by=[0,1],ascending=True) 
#0번열을 기준으로 정렬 0열 값이 동일 할때는 1열 값 기준으로 다시 정렬


# In[55]:


# df  확인
df


# - 데이터프레임의 index를 기준으로 정렬

# In[57]:


df.sort_index()
df.sort_index(ascending=False)


# # 데이터 프레임 조작 함수 정리

# ### 행/열 합계
# - df.sum() 함수 사용
# - 행과 열의 합계를 구할때는 sum(axis=0/1) - axis는 0이 기본
# 
# 
# - 각 열의 합계를 구할때는 sum(axis=0)
# - 각 행의 합계를 구할때는 sum(axis=1)

# In[59]:


# 예제 DF 생성
#4행 8열의 데이터프레임 작성, 난수를 발생시키고
#0-9범위에서 매번 같은 난수 발생되어 반환되도록 설정
np.random.seed(1)
df2=pd.DataFrame(np.random.randint(10,size=(4,8)))
df2


# In[61]:


# df2의 각열의 합계 = sum(axis=0)
df2.sum(axis=0) # 시리즈 반환
df2.sum() # axis 의 기본값은 0 -> 각 열의 합계


# In[62]:


#  df2 의 각행의 합계
df2.sum(axis=1)


# - 데이터프레임 기본 함수 확인

# In[73]:


# 평균/최대/최소 값을 구하는 함수 : 각열이나 또는 행 단위로 연산 진행

df2.mean(axis=1)
df2.max(axis=1)
df2.min(axis=1)


# #### df의 새로운 행과 열 추가 예제
# 
# -  새로운 열 추가 : 기본인덱싱 사용 
#     - df['새로운 열 이름'] = 값
#     
#     
# -  새로운 행 추가 : loc 인덱서
#     - df.loc['새로운 행 인덱스'] = 값
# 

# In[63]:


df2


# In[65]:


# 위 데이터프레임에 각 열의 합계를 구해서 마지막 행으로 추가하시오
# 새로운행 추가 (loc 인덱서 사용이 가장 간단함)
# 행이름 : ColTotal

df2.loc['ColTotal']=df2.sum()
df2


# In[70]:


# df2 데이터프레임에 각 행의 합계를 구해서 마지막 열로 추가하시오
# 열 이름 : RowSum
df2["RowSum"]=df2.sum(axis=1) #원본 반영


# In[68]:


# del df2['RowSum']


# In[71]:


df2


# ### 행/열 삭제 - df의 drop() 사용 예제
# 
# 
# - df.drop('행이름',0) : 행삭제 
#     - 행삭제 후 df로 결과를 반환
# - df.drop('열이름',1) : 열 삭제
#     - 열삭제 후 df로 결과를 반환
#     
#     
# - 원본에 반영되지 않으므로  원본수정하려면 저장 해야 함
# 
# 
# - del 명령어는 삭제 명령어 이며 원본을 변경 함

# In[74]:


df2


# In[75]:


df2.drop('ColTotal',0) # 행 삭제후 결과를 반환
df2 #원본 데이터에는 반영되지 않는다


# In[76]:


df2.drop('RowSum',1) # 해당열 삭제한 결과를 반환
df2 # 원본에는 반영 되지 않는다


# ### NaN 값 처리 함수
# 
# 
# - df.dropna(axis=0/1)
#     - NaN 값이 있는 열 또는 행을 삭제
#     - 원본 반영되지 않음
#     
#     
# - df.fillna(채우려는값)
#     - NaN값을 정해진 값으로 채움
#     - 원본 반영  되지 않음

# In[81]:


# df2에 결측치 값 적용
df2.iloc[0,0] = np.nan
df2.iloc[2,7] = np.nan
df2


# In[82]:


# NaN이 포함된 모든 행을 삭제
df2.dropna()
df2 #원본 반영 안됨


# In[83]:


# NaN이 포함된 모든 열을 삭제
df2.dropna(axis=1)
df2 #원본 반영 안됨


# In[86]:


df2.fillna(0)
df2
df2.fillna(5)


# In[88]:


df2.fillna('a')[0].dtype


# In[90]:


# df의 원소 dtype 변경 함수 
# df.astype(자료형) int/float

df2.fillna(0).astype(int)
df2
df2.fillna(5).astype(float)


# ### 열 또는 행에 동일한 연산 반복 적용할 때 : apply() 함수
# - apply() 함수는 DataFrame의 행이나 열에 복잡한 연산을 vectorizing할 수 있게 해주는 함수로 매우 많이 활용되는 함수임
# - 동일한 연산을 모든열에 혹은 모든 행에 반복 적용하고자 할때 사용
# 
# - apply(반복적용할 함수, axis=0/1)
#     - 0 : 열마다 반복
#     - 1 : 행마다 반복 
#     - 생략시 기본값 : 0

# In[91]:


#예제 df 생성
df3 = pd.DataFrame({
    'a':[1,3,4,3,4],
    'b':[2,3,1,4,5],
    'c':[1,5,2,4,4]
})
df3


# In[92]:


# df3의 각 열에 대해 np.sum 이라는 함수를 반복 적용하는 코드를 생성하시오

df3.apply(np.sum)


# In[93]:


# df3의 각 행에 대해 np.sum 이라는 함수를 반복 적용하는 코드를 생성하시오

df3.apply(np.sum, 1)


# In[94]:


df3.sum(axis=0) # 위 코드와 같은 결과를 반환


# - 데이터프레임의 기본 집계함수(sum, min, max, mean 등)들은 행/열 단위 벡터화 연산을 수행함
#     - apply() 함수를 사용할 필요가 없음

# - 일반적으로 apply() 함수 사용은 복잡한 연산을 해결하기 위한 lambda 함수나 사용자 정의 함수를 각 열 또는 행에 일괄 적용시키기 위해 사용

# ##### 1회성 함수인 lambda 함수를 apply()에 사용하는 예제

# In[98]:


df3


# In[95]:


# 집합 데이터(시리즈)의 최대값과 최소값의 차이를 구하는 연산을 lambda 함수로 정의
diff = lambda x: x.max()-x.min()


# In[97]:


# df3의 a열의 최대값과 최소값의 차이를 위에서 생성한 lambda 함수를 이용해서 구하시오

diff(df3['a'])


# In[99]:


# apply 함수를 이용하여 위에서 생성한 lambda diff를 df3의 모든 열에 반복 적용하여 
# 모든 열의 최대값과 최소값의 차이를 구하시오

df3.apply(diff,0)


# In[100]:


# apply 함수를 이용하여 위에서 생성한 lambda diff를 df3의 모든 행에 반복 적용하여 
# 모든 행의 최대값과 최소값의 차이를 구하시오

df3.apply(diff,1)


# In[101]:


# 다른방법 : 직접 연산

#df3 각 행에 대하여 최대값과 최소값의 차이를 구하시오
df3.max(axis=1) - df3.min(axis=1)


# In[103]:


# df3의 각 열의 데이터에 대해서 카테고리 세기를 수행하시오
df3

# apply() 함수를 사용해서 value_counts() 적용 test
df3.apply(pd.value_counts)


# In[104]:


# df3의 각 열의 데이터에 대해서 카테고리 세기를 수행하고 NaN값은 0 으로 변환 후 
# 반환되는 전체 데이터의 타입을 정수로 변환하시오.

df3.apply(pd.value_counts).fillna(0).astype(int)


# #### 관측 데이터 값을 범주형(카테고리) 값으로 변환
# - 값의 크기를 기준으로하여 카테고리 값으로 변환하고 싶을 때
#     - cut(data, bins, label)
#     
#     - data : 구간을 나눌 실제 관측 값, bins : 구간 경계 값, label : 카테고리 값
#     
#     

# In[105]:


ages= [0, 0.5, 4, 6, 4, 5, 2, 10, 21, 37, 15, 38, 31,61, 20, 41, 31, 100]


# In[106]:


#label : 카테고리 명
labels=['영유아','미성년자','청년','중년','장년','노년']

# bins : 구간 경계값 설정
bins = [0,4,15,25,35,60,100]

# 0 < 영유아 <= 4
# 4 < 미성년자 <= 15


# In[109]:


# 함수 적용해서 카테고리 생성
cats = pd.cut(ages, bins=bins, labels=labels)
cats
type(cats)


# In[110]:


list(cats)


# ##### Categorical 클래스 객체
# - 카테고리명 속성 : Categorical.categories
# - 코드 속성 : Categorical.codes 
#     - 인코딩한 카테고리 값을 정수로 갖는다.

# In[112]:


type(cats)


# In[113]:


cats.categories


# In[114]:


cats.codes # codes의 원소가 -1이면 카테고리를 정하지 못했음을 의미(결측치)


# In[115]:


# age 리스트를 이용해서  df 생성

df4 =  pd.DataFrame(ages, columns = ['ages'])
df4


# In[116]:


df4['연령대'] = pd.cut(df4.ages, bins, labels=labels)
df4


# ##### 구간 경계선을 지정하지 않고 데이터 개수가 같도록 지정한 수의 구간으로 분할하기 :  qcut()  
# 
# - 형식 : pd.qcut(data,구간수,labels=[d1,d2....])
#     
#     
#     - 예)1000개의 데이터를 4구간으로 나누려고 한다면
#         - qcut 명령어를 사용 : 한 구간마다 250개씩 나누게 된다.
#         - 예외)같은 숫자인 경우에는 같은 구간으로 처리한다.
# 

# In[132]:


# 랜덤정수 20개를 생성하고 생성된 정수를 4개의 구간으로 나누시오.

# 각 구간의 label은 Q1,Q2,Q3,Q4 로 설정하시오.

#랜덤정수 생성 : 범위 0-19, size =20
#seed 설정해서 재 실행해도 랜덤정수가 변하지 않도록 생성

# seed  설정
np.random.seed(2)

# 랜덤 정수 생성
data = np.random.randint(20, size = 20)

data


# In[133]:


qcat = pd.qcut(data, 4, labels=['Q1','Q2','Q3','Q4'])
qcat


# In[135]:


pd.value_counts(qcat)


# In[134]:


list(qcat)


# ### 인덱스 설정 함수
# #### 데이터 프레임 인덱스 설정을 위해 set_index(), reset_index()
# - set_index() : 기존 행 인덱스를 제거하고 데이터 열 중
# 하나를 인덱스로 설정해주는 함수
# - reset_index() : 기존 행인덱스를 제거하고 기본인덱스로 변경
# - 기본인덱스 : 0부터 1씩 증가하는 정수 인덱스
#     - 따로 설정하지 않으면 기존 인덱스는 데이터열로 추가 됨

# In[ ]:


#예제 데이터프레임 생성
df3 = pd.DataFrame({
    'a':[1,3,4,3,4],
    'b':[2,3,1,4,5],
    'c':[1,5,2,4,4]
})
df3


# In[138]:


df3


# In[141]:


# df3의 a열을 인덱스로 설정
df3.set_index('a') # 원본에 반영되지 않으므로 필요하면 저장해야 함
df3

df3 = df3.set_index('a')
df3


# In[142]:


df3


# In[145]:


# df3의 행 인덱스를 제거하고 기본 인덱스로 설정 -reset_index()
df3.reset_index()

# 기존 index의 처리 : drop=True -> 기존 인덱스 제거
#                   : 명시하지 않으면 열 data로 정의

df3.reset_index(drop=True)


# ##### index 원소 변경하기 : df.rename()  사용
# - df.reanme(index={현재인덱스:바꿀인덱스})

# In[149]:


df3 = df3.reset_index(drop=True)
df3


# In[153]:


# df3.rename(index={0:'1반'})
# df3.rename(columns={'b':'학생'})
df3.rename(columns={'b':'학생'},index={0:'1반'})
df3 # 원본 반영 안됨


# ### 리스트 내포 연산

# #### 리스트 내포 for문 : 문법
# - [표현식(연산식) for 항목 in 반복가능객체 if 조건문]
# - if 조건문은 생략 가능하다.
# - 반복가능객체 : 리스트, 튜플,딕셔너리,range()등

# In[156]:


a = [1,2,3,4]

# 위 a 리스트의 각 원소에 대해 2배한 원소값을 만들고 result라는 변수에 저장하시오.

# [1,2,3,4] *2 #[1, 2, 3, 4, 1, 2, 3, 4]

result = []

for num in a : 
    result.append(num*2)
    
result


# In[157]:


# 내포 for 문 사용
result2 = [num*2 for num in a ]
result2


# In[ ]: